
spring.application.name: invoice_service

#server conf
server:
  servlet.context-path: /invoice_service/api/v1
  port: 8080
  address: localhost

#datasource conf
spring.datasource:
  url: jdbc:postgresql://localhost:5432/invoice_service
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: 45678

#jpa - hibernate conf
spring.jpa:
  show-sql: true
  properties.hibernate:
    format_sql: true
    validator:
      apply_to_ddl: true
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
    globally_quoted_identifiers: true
  generate-ddl: true
  hibernate.ddl-auto: update
