
spring.application.name: invoice_service

#server conf
server:
  servlet.context-path: /invoice_service/api/v1
  port: 8080
  address: localhost

#datasource conf
spring.datasource:
  url: jdbc:mysql://localhost:3306/invoice_service
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 0123456789

#jpa - hibernate conf
spring.jpa:
  show-sql: true
  properties.hibernate:
    format_sql: true
    validator:
      apply_to_ddl: true
    dialect: org.hibernate.dialect.MySQL8Dialect
    globally_quoted_identifiers: true
  generate-ddl: true
  hibernate.ddl-auto: update